// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBuM7K-qExf5ohqtawHkUU1ULn07Eulwc0',
    appId: '1:1064605989793:web:8de6eea96d35c0c3dda9e0',
    messagingSenderId: '1064605989793',
    projectId: 'fitapp-9dc6e',
    authDomain: 'fitapp-9dc6e.firebaseapp.com',
    storageBucket: 'fitapp-9dc6e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwJ_UCrSBI0ZN23E7BAezmg1GDwr0MCbY',
    appId: '1:1064605989793:android:0bbf7a59969a3849dda9e0',
    messagingSenderId: '1064605989793',
    projectId: 'fitapp-9dc6e',
    storageBucket: 'fitapp-9dc6e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZYR-cUydOzyIsGULAyMjIU64mL4ilnn4',
    appId: '1:1064605989793:ios:e14f4450daf4e7fddda9e0',
    messagingSenderId: '1064605989793',
    projectId: 'fitapp-9dc6e',
    storageBucket: 'fitapp-9dc6e.appspot.com',
    iosClientId: '1064605989793-lt8jo2c4jtr1m6et8tnp39kd5u8l4knt.apps.googleusercontent.com',
    iosBundleId: 'com.example.fitapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZYR-cUydOzyIsGULAyMjIU64mL4ilnn4',
    appId: '1:1064605989793:ios:e14f4450daf4e7fddda9e0',
    messagingSenderId: '1064605989793',
    projectId: 'fitapp-9dc6e',
    storageBucket: 'fitapp-9dc6e.appspot.com',
    iosClientId: '1064605989793-lt8jo2c4jtr1m6et8tnp39kd5u8l4knt.apps.googleusercontent.com',
    iosBundleId: 'com.example.fitapp',
  );
}
